baseURL = "https://ch-skz.netlify.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "CHANNEL SKZ"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false
sectionPagesMenu = "main"
enableGitInfo = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#gtagId = "G-0MPEJM381H"

[params]
year = 2017
years = [2017, 2018, 2019, 2020, 2021]
title = "CHANNEL SKZ"
author = "daisukijeu"
description = "Channel SKZ is a fanmade masterlist of Stray Kids video contents such as music videos, album promotions, shows, V LIVEs, etc."
banner = "/images/site-cover.jpg"
profilePicture = "images/icon.png"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css", "css/timeline.css"]
customJs = []
mainSections = ["artistry", "shows", "vlive"]
images = ["images/banner-kd.jpg"]
doNotLoadAnimations = true
displayMode = "light"
ignoreErrors = ["error-remote-getjson"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

forLive = "V LIVE"



## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@alexbilz.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Artistry"
  weight = 2
  identifier = "artistry"
  url = "/artistry/"

  [[menu.main]]
  name = "Shows"
  weight = 3
  identifier = "shows"
  url = "/shows/"

  [[menu.main]]
  name = "V Live"
  weight = 4
  identifier = "vlive"
  url = "/vlive/"

  [[menu.main]]
  name = ""
  weight = 5
  identifier = "posts"
  url = "/posts/"
  [menu.main.params]
    class = "hidden"

  [[menu.main]]
  name = ""
  weight = 5
  identifier = "site-update"
  url = "/site-update/"
  [menu.main.params]
    class = "hidden"

  [[menu.main]]
  name = ""
  weight = 5
  identifier = "support"
  url = "/support/"
  [menu.main.params]
    class = "hidden"
